<h1>'함께실습$1'  <h1>시리즈(Series) 만들기

In [23]:
import pandas as pd

# 시리즈에 딕셔너리를 넣는 경우

s1 = pd.Series(
{'김' : 100, '나': 141, '박' :129, '이' : 124}
)

s1.name = '수학'

print(s1)
print('=' * 50)

김    100
나    141
박    129
이    124
Name: 수학, dtype: int64


In [12]:
s2 = pd.Series(
{'김' : 30, '나': 5, '박' :1239, '이' : 141}
)

print(s2)
print('=' * 50)

김      30
나       5
박    1239
이     141
dtype: int64


In [14]:
# 시리즈에 인덱스를 지정하지 않고(딕셔너리가 아닌) 리스트를 준 경우

s3 = pd.Series(
[8,3,12,2]
)

s3.name = '국어'

print(s3)
print('=' * 50)

0     8
1     3
2    12
3     2
Name: 국어, dtype: int64


In [16]:
# Name과 index 모두 지정하지 않는 경우

s4 = pd.Series(
[30, 5, 1239, 141]
)

print(s4)

0      30
1       5
2    1239
3     141
dtype: int64


<h1>'함께실습$2'  <h1>데이터프레임(DataFrame) 만들기

In [17]:
df = pd.DataFrame({ '출생지' : ['한국', '미국'], '나이' : [20, 30]})
df

출생지  나이
0  한국  20
1  미국  30

<h1>'함께실습$3'  <h1>DataFrame에 행과 열 추가하기

In [18]:
# 열 추가

df['성별'] = ['여', '남']
df

출생지  나이 성별
0  한국  20  여
1  미국  30  남

In [19]:
# 행 추가

df.loc[2] = ['일본', 25, '여']
df

출생지  나이 성별
0  한국  20  여
1  미국  30  남
2  일본  25  여

<h1>'함께실습$4'  <h1>Series로 DataFrame 만들기

In [24]:
df2 = pd.DataFrame(s1)

df2['영어'] = s2
df2['미술'] = [1, 2, 3, 4]

df2

수학    영어  미술
김  100    30   1
나  141     5   2
박  129  1239   3
이  124   141   4

<h1>'함께실습$5'  <h1>원하는 열, 행 고르기

In [28]:
# 열 고르기

df2[['수학', '미술']]

수학  미술
김  100   1
나  141   2
박  129   3
이  124   4

In [29]:
# 행 고르기

df2.loc[['김', '박']]

수학    영어  미술
김  100    30   1
박  129  1239   3

In [32]:
# 행/열 함께 고르기

df2.loc[['김'], ['미술']]

미술
김   1

<h1>'함께실습$6'  <h1>계산기능

In [33]:
df2

수학    영어  미술
김  100    30   1
나  141     5   2
박  129  1239   3
이  124   141   4

In [35]:
# 열 모든 성분 연산
# df2.sum(axis=0)와 같습니다.

print(df2.sum())

수학     494
영어    1415
미술      10
dtype: int64


In [37]:
# 행 모든 성분 연산

print(df2.mean(axis=1))

김     43.666667
나     49.333333
박    457.000000
이     89.666667
dtype: float64


In [38]:
# 행 연산

print(df2['수학'].mean())

123.5


In [39]:
# 열 열산

print(df2.loc['김'].sum())

131


<h1>'미션$1'  <h1>직접 입력하고 어떤 명령인지 알아보세요

> ,(콤마)를 기준으로 왼쪽은 행, 오른쪽은 열을 필터링합니다.  
> **'영어 점수가 100점 이상인 학생만 뽑아 그들의 수학점수 평균을 보여달라'**

In [40]:
print(df2.loc[df2['영어'] >= 100, '수학'].mean())

126.5


<h1>'자율$1'  <h1>내 마음대로 배열 만들기

In [46]:
import numpy as np

a = np.array([1,2,3,])

b = np.array([ [1,2,3],[4,5,6] ])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


<h1>'자율$2'  <h1>0으로 가득찬 배열 만들기

In [48]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

<h1>'자율$3'  <h1>배열의 형태 알기

In [49]:
a = np.array([[1,2,3,4], [5,6,7,8] , [9,10,11,12]])
a.shape

(3, 4)

<h1>'자율$4'  <h1>배열의 필요한 부분 자르기

In [50]:
a = np.array(['a', 'b', 3, 4])
print(a[1:3])

['b' '3']


In [52]:
b = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 0행부터 1행까지, 1열부터 2열까지
print(b[0:2, 1:3])

[[2 3]
 [6 7]]


In [53]:
# 모든 행, 1열부터 2열까지

print(b[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [54]:
# 2행부터 끝행, 모든 열

print(b[1:, :])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
# 전부

print(b[:,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<h1>'자율$5'  <h1>내용 수정하기

In [56]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[2,3] = 1 # 파이썬 특징대로 2행 3열이 아니라, 3행 4열
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1]])

<h1>'자율$6'  <h1>내용 수정 후 특정 부분만 출력

In [ ]:
mission = np.array()